### PR TITLE
Feature/Include PlantUML diagrams at arbitrary positions in doc

### LINKED ISSUE #21: Provide option to include PlantUML diagrams at arbitrary positions in doc
At the moment the user is forced to either have all PlantUML images at the very top of a page, or at the very bottom (option `diagramsOnTop`).

But what if I want to be able to freely distribute the diagrams on the page? E.g. what if I want to have an introduction headline and paragraph, followed by diagram number 1, then some more text, then diagram number 2, etc.

Since I can simply include images myself using the syntax `diagram` the easiest solution would probably to have a CLI argument that *disables* the automatic inclusion of the converted `puml` files.

### PR DESCRIPTION
**Pull request by sju66**
Addition of the possibility of including diagrams at an arbitrary position via the use of markdown syntax !\[](**_**_diagram_**.puml**). 

Fixes #21

### CODE REVIEW

**Comment by adrianvlupu** [comment]
Thanks for the pull request, I'll come back to this after I push all the other PRs

**Comment by hkdobrev** [comment]
@adrianvlupu Is it possible to review this at this time? Thank you!

**Comment by MickeJohannesson** [comment]
I have done an update to this PR but not able to commit it.
Changes made:

- Added support to add an PUML diagram in the page in format ! [name] (name.puml) and it will be excluded from the normal rendering of the page. All other will be in top/bottom
- Merged from latest master and fixed the merge problems.
- Removed the extra config settings added in this PR, instead use current one (PLANTUML_SERVER_URL)
- Updated with latest PlantUML (plantuml-1.2022.1.jar)
- Updated some NPMs: md-to-pdf and joi
- Fixed "Download link" in deep folder structures (had problem on level 3 where it lost subfolders)
- Added "new line" on Download link/Go to link (before they came next to the diagram instead of under it)
- Added support for DITAA diagram type (only PNG is supported)

If someone could give me a hint on getting this into this PR or if I need to push it as a new PR

**Comment by huyz** [comment]
@MickeJohannesson Your changes look quite useful.  But they seem like multiple PRs.  Can you break it up and submit PRs separately?

**Comment by MickeJohannesson** [comment]
The problem is that all changes (more or less) are made in the build.js file. And I have done them in the version from this PR.
Some are of course not needed (like PlantUML and NPM update).
But to make for example DITAA support work it can not be separated in the main version of the build.js in a simple way
What I instead could do is do a first commit on a new PR and then commit the "addons" as separate commits.

**Comment by vellala2000** [comment]
This seems like very handy feature and its pending for some time. If we could figure out conflicts and a path forward that would be awesome. Please let me know if there is anything i can do to help

**Comment by adrianvlupu** [comment]
Thanks for the implementation. 

I couldn't merge it properly but the functionality is there from another PR (that included your changes) and my refactoring.

You can include diagrams using `name` where `diagramName` is variable.

**Pull request closed without merging**
