### PR TITLE
Diagrams at arbitrary position and DITAA diagrams

### PR DESCRIPTION
**Pull request by MickeJohannesson**
Used base from #28 and done some modifications to it
Fixes the issure #21 

- Added support to add an PUML diagram in the page in format ! [name] (name.puml) and it will be excluded from the normal rendering of the page. All other will be in top/bottom
- Merged from latest master and fixed the merge problems.
- Removed the extra config settings added in this PR, instead use current one (PLANTUML_SERVER_URL)
- Updated with latest PlantUML (plantuml-1.2022.1.jar)
- Updated some NPMs: md-to-pdf and joi
- Fixed "Download link" in deep folder structures (had problem on level 3 where it lost subfolders)
- Added "new line" on Download link/Go to link (before they came next to the diagram instead of under it)
- Added support for DITAA diagram type (only PNG is supported)

### CODE REVIEW

**Comment by MickeJohannesson** [comment]
Added in the fix for #52

**Comment by vellala2000** [comment]
This MR has some great features that I am looking forward to use.  However the MR has lot of changes which make it hard to review. May be there is an opportunity to speed up this process if this is split this into smaller chunks.

**Review by vellala2000 — CHANGES_REQUESTED** [review]
This MR has some great features that I am looking forward to use. However the MR has lot of changes which make it hard to review. May be there is an opportunity to speed up this process if this is split this into smaller chunks.

**Comment by biznuge** [comment]
@MickeJohannesson - Love the new position your diagram anywhere in the .md file. One thing I noted is the command line now requires input. it there a non-interactive flag that we can use to bypass this for CI builds etc.

Again. Nice PR. :)

**Comment by vellala2000** [comment]
I had the same problem running the build in the pipeline. However its resolved after adding the new configs and removed file hashes from .c4builder. Not exactly 100% sure which one did the trick. Here are the properties i currently have
```
{
	"plantumlVersion": "latest",
	"projectName": "",
	"homepageName": "",
	"repoUrl": "",
	"rootFolder": "",
	"distFolder": "",
	"generateMD": false,
	"generatePDF": false,
	"generateCompleteMD": true,
	"generateCompletePDF": false,
	"generateWEB": true,
	"supportSearch": true,
	"webTheme": "//unpkg.com/docsify/lib/themes/vue.css",
	"docsifyTemplate": "",
	"webPort": "3000",
	"pdfCss": "",
	"includeBreadcrumbs": true,
	"includeLinkToDiagram": false,
	"diagramsOnTop": true,
	"embedDiagram": false,
	"generateLocalImages": true,
	"plantumlServerUrl": "https://www.plantuml.com/plantuml",
	"diagramFormat": "svg",
	"charset": "UTF-8",
	"hasRun": true,
	"excludeOtherFiles": false
}
```

**Pull request merged**
